server:
  port: 8080

spring:
  application:
    name: feign-client-example

# Set to true when EUREKA discovery server is present.
eureka:
  client:
    fetchRegistry: false
    register-with-eureka: false